# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-04-19 09:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='location',
            field=models.CharField(default='nguk', max_length=255),
            preserve_default=False,
        ),
    ]
